server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/essrakh/config-repo.git
          clone-on-start: true
          default-label: main
