server:
  port: 8083

spring:
  application:
    name:gateway-service
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://customer
          predicates:
            - Path=/api/v1/customers/**
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/api/v1/orders/**
        - id: products
          uri: http://products
          predicates:
            - Path=/api/v1/products/**
  discovery:
    enabled: true  # Active la découverte des services
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
